ARG FEDORA_VERSION=33
FROM fedora:${FEDORA_VERSION}

ADD rootfs /

ARG SSHD_PACKAGE=openssh-server
ARG SSHD_PORT=64022

RUN dnf -y install ${SSHD_PACKAGE}\
 && dnf clean all\
\
 && echo "Port ${SSHD_PORT}" > /etc/ssh/sshd_config.d/port.conf

EXPOSE ${SSHD_PORT}
ENTRYPOINT ["/entrypoint.sh"]
