ARG FEDORA_VERSION=latest
FROM fedora:${FEDORA_VERSION}

ADD rootfs /

ARG DNF_INSTALL_PACKAGES
ARG SSHD_PORT

RUN dnf -y install openssh-server ${DNF_INSTALL_PACKAGES}\
 && dnf clean all\
\
 && echo "Port ${SSHD_PORT}" > /etc/ssh/sshd_config.d/port.conf

EXPOSE 64022
ENTRYPOINT ["/entrypoint.sh"]
