version: '2'
services:
  sut:
    depends_on:
      - sshd
    build:
      context: ./tests
      dockerfile: Dockerfile-sut
      args:
        ADD_PACKAGES: make openssh-client
    environment:
      TARGET_HOST: sshd
      TARGET_PORT: "${SSHD_PORT}"
#  ssh-keygen -C 'test-id' -f ./test-rsa -N "" -v
#  cat ./test-rsa | base64 | sed -e ':a;N;$!ba;s/\n//g'
      PRIVATE_KEY_BASE64: "${TEST_PRIVATE_KEY_BASE64}"
    command: tests

  sshd:
    image: ${IMAGE_NAME}
    environment:
      AUTHORIZED_KEYS: "${TEST_PUBLIC_KEY}"
      SSHD_PORT: "${SSHD_PORT}"
