ARG ALPINE_VERSION=3.12.0
FROM alpine:${ALPINE_VERSION}

ADD rootfs /

ARG SSHD_PACKAGE=openssh-server
ARG SSHD_PORT=64022

RUN apk add --update --no-cache ${SSHD_PACKAGE}\
 && rm  -vrf /var/cache/apk/*\
\
 && echo "Port ${SSHD_PORT}" > /etc/ssh/sshd_config.d/port.conf\
 && echo 'Include /etc/ssh/sshd_config.d/*.conf' >> /etc/ssh/sshd_config\
 && echo root:root | chpasswd

EXPOSE ${SSHD_PORT}
ENTRYPOINT ["/entrypoint.sh"]
