#!/bin/sh

echo "------ HOOK START - BUILD -------"

source ./.env

BUILD_ARGS="--build-arg SSHD_PORT=${SSHD_PORT}"

echo "${DOCKER_TAG}" | grep '-fedora$'  && DISTRIB="fedora" && BUILD_ARGS="${BUILD_ARGS} --build-arg SSHD_PACKAGE=${SSHD_FEDORA_PACKAGE}"
echo "${DOCKER_TAG}" | grep '-alpine$'  && DISTRIB="alpine" && BUILD_ARGS="${BUILD_ARGS} --build-arg SSHD_PACKAGE=${SSHD_ALPINE_PACKAGE}"

docker build ${BUILD-ARGS} -t ${IMAGE_NAME} -f Dockerfile-${DISTRIB:-alpine} ./sshd/

echo "------ HOOK END - BUILD -------"
