#!/usr/bin/env -S podman-compose -f

# ./compose.yaml up -d --force-recreate
# ./compose.yaml build --no-cache

services:
  sshd:
    image: docker.io/kran0/dropbear:tiny
    build:
      context: container
    ports:
      - 64022:64022
    environment:
      AUTHORIZED_KEYS: |
        #main key
        ssh-rsa example-key login@hostname.localdomain
