#!/usr/bin/env -S podman-compose -f

# ./compose.yaml up -d --force-recreate
# ./compose.yaml build --no-cache

version: '2'
services:
  sshd:
    image: docker.io/kran0/sshd:8.3p1-alpine
    restart: always
    ports:
      - "${SSHD_EXTERNAL_PORT}:${SSHD_PORT}"
    env_file: .env
    network_mode: "host"
