
services:
  sshd:
    image: docker.io/kran0/dropbear:latest
    build:
      context: container
      args:
        - FEDORA_RELEASE=latest
    ports:
      - 64022:64022
    environment:
      AUTHORIZED_KEYS: |
        #main key
        ssh-rsa example-key login@hostname.localdomain
    healthcheck:
      test: sh -c 'exec test "$(ps -o comm= 1)" "==" "dropbear"' # dropbear pid=1
      interval: 1s
      retries: 5
