
services:
  sshd:
    image: docker.io/kran0/dropbear:latest
    build:
      context: container
    ports:
      - 64022:64022
    environment:
      AUTHORIZED_KEYS: |
        #main key
        ssh-rsa example-key login@hostname.localdomain

    healthcheck:
      test: sh -c "ps -o pid=,comm= | grep -q '^ *1 dropbear$'" # pid=1 comm=dropbear
